#!/usr/bin/env python3
"""Create validated meso-erythritol and threitol inputs for MSLD tests.

The existing ``eryth`` coordinates are (2S,3S), so they are retained as the
threitol input.  Meso-erythritol is generated by reflecting the O3/H5/H9
group through the C2-C3-C4 plane.  This is an isometry around C3: it preserves
the relevant bond lengths and angles while changing only C3 configuration.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
from rdkit import Chem


HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent
INPUTS = HERE / "inputs"
CHIRAL_IMPROPER_K = 50.0  # kcal mol-1 rad-2
CHIRAL_IMPROPER_ANGLE = 32.60  # degrees; measured from the validated inputs


def atom_names_from_mol2(path: Path) -> list[str]:
    names: list[str] = []
    in_atoms = False
    for line in path.read_text().splitlines():
        if line.strip() == "@<TRIPOS>ATOM":
            in_atoms = True
            continue
        if line.strip() == "@<TRIPOS>BOND":
            break
        if in_atoms and line.strip():
            names.append(line.split()[1])
    return names


def reflect_point(point: np.ndarray, origin: np.ndarray, normal: np.ndarray) -> np.ndarray:
    return point - 2.0 * np.dot(point - origin, normal) * normal


def write_mol2_with_coordinates(template: Path, output: Path, molecule_name: str, mol: Chem.Mol) -> None:
    conformer = mol.GetConformer()
    lines: list[str] = []
    in_atoms = False
    atom_index = 0
    title_pending = False

    for line in template.read_text().splitlines():
        if line.strip() == "@<TRIPOS>MOLECULE":
            title_pending = True
            lines.append(line)
            continue
        if title_pending:
            lines.append(molecule_name)
            title_pending = False
            continue
        if line.strip() == "@<TRIPOS>ATOM":
            in_atoms = True
            lines.append(line)
            continue
        if line.strip() == "@<TRIPOS>BOND":
            in_atoms = False
            lines.append(line)
            continue
        if in_atoms and line.strip():
            fields = line.split()
            point = conformer.GetAtomPosition(atom_index)
            atom_index += 1
            line = (
                f"{int(fields[0]):7d} {fields[1]:<8s} "
                f"{point.x:10.4f} {point.y:10.4f} {point.z:10.4f} "
                f"{fields[5]:<8s} {int(fields[6]):4d} {fields[7]:<8s} "
                f"{float(fields[8]):10.6f}"
            )
        lines.append(line)

    if atom_index != mol.GetNumAtoms():
        raise RuntimeError(f"MOL2/SDF atom-count mismatch: {atom_index} != {mol.GetNumAtoms()}")
    output.write_text("\n".join(lines) + "\n")


def write_sdf(path: Path, name: str, mol: Chem.Mol) -> None:
    output = Chem.Mol(mol)
    output.SetProp("_Name", name)
    writer = Chem.SDWriter(str(path))
    writer.write(output)
    writer.close()


def cip_centres(mol: Chem.Mol) -> list[tuple[int, str]]:
    Chem.AssignStereochemistry(mol, cleanIt=True, force=True)
    return Chem.FindMolChiralCenters(mol, includeUnassigned=True, includeCIP=True)


def copy_force_field_files(source_stem: str, destination_stem: str) -> None:
    for suffix in ("rtf", "prm", "str"):
        shutil.copyfile(SOURCE / f"{source_stem}.{suffix}", INPUTS / f"{destination_stem}.{suffix}")


def add_c3_chirality_restraint(
    stem: str,
    improper_atoms: tuple[str, str, str, str],
    improper_types: tuple[str, str, str, str],
) -> None:
    """Add an endpoint-specific, signed C3 improper to RTF/PRM/stream files.

    The meso and threo atom orders are reversed so their opposite Cartesian
    configurations have the same positive equilibrium improper.  This avoids
    the incorrect use of a conventional 0-degree planar improper at a
    tetrahedral carbon.
    """
    rtf_path = INPUTS / f"{stem}.rtf"
    prm_path = INPUTS / f"{stem}.prm"
    atom_line = "IMPR " + " ".join(improper_atoms)
    type_line = (
        "%-7s %-7s %-7s %-7s %8.3f  0 %8.2f"
        % (*improper_types, CHIRAL_IMPROPER_K, CHIRAL_IMPROPER_ANGLE)
    )

    rtf_text = rtf_path.read_text()
    if "\nEND" not in rtf_text:
        raise RuntimeError(f"Could not find topology END marker in {rtf_path}")
    rtf_text = rtf_text.replace(
        "\nEND",
        "\n\n! Signed tetrahedral restraint for C3 stereochemistry\n"
        + atom_line
        + "\n\nEND",
        1,
    )
    rtf_path.write_text(rtf_text)

    prm_text = prm_path.read_text()
    marker = "IMPROPERS\n"
    if marker not in prm_text:
        raise RuntimeError(f"Could not find IMPROPERS section in {prm_path}")
    prm_text = prm_text.replace(
        marker,
        marker
        + "! Signed tetrahedral C3 restraint; not a planar improper\n"
        + type_line
        + "\n",
        1,
    )
    prm_path.write_text(prm_text)

    # Keep the convenience stream file consistent with the RTF/PRM pair.
    (INPUTS / f"{stem}.str").write_text(
        rtf_text.rstrip() + "\n\n" + prm_text.rstrip() + "\nRETURN\n"
    )


def main() -> None:
    INPUTS.mkdir(parents=True, exist_ok=True)

    source_sdf = SOURCE / "eryth.sdf"
    source_mol2 = SOURCE / "eryth.mol2"
    threitol = Chem.SDMolSupplier(str(source_sdf), removeHs=False)[0]
    if threitol is None:
        raise RuntimeError(f"RDKit could not read {source_sdf}")

    names = atom_names_from_mol2(source_mol2)
    if len(names) != threitol.GetNumAtoms():
        raise RuntimeError("MOL2 and SDF atom ordering are inconsistent")
    index = {name: i for i, name in enumerate(names)}

    starting_centres = cip_centres(threitol)
    if sorted(code for _, code in starting_centres) != ["S", "S"]:
        raise RuntimeError(f"Expected the existing eryth file to be (S,S), got {starting_centres}")

    meso = Chem.Mol(threitol)
    conformer = meso.GetConformer()

    def xyz(atom_name: str) -> np.ndarray:
        point = conformer.GetAtomPosition(index[atom_name])
        return np.array([point.x, point.y, point.z], dtype=float)

    origin = xyz("C3")
    normal = np.cross(xyz("C2") - origin, xyz("C4") - origin)
    normal /= np.linalg.norm(normal)
    for atom_name in ("O3", "H5", "H9"):
        reflected = reflect_point(xyz(atom_name), origin, normal)
        conformer.SetAtomPosition(index[atom_name], reflected)

    Chem.RemoveStereochemistry(meso)
    Chem.AssignAtomChiralTagsFromStructure(meso, confId=0, replaceExistingTags=True)
    meso_centres = cip_centres(meso)
    if sorted(code for _, code in meso_centres) != ["R", "S"]:
        raise RuntimeError(f"Generated structure is not meso (R,S): {meso_centres}")

    write_sdf(INPUTS / "threitol.sdf", "threitol_(2S,3S)", threitol)
    write_sdf(INPUTS / "meso_erythritol.sdf", "meso_erythritol_(2S,3R)", meso)
    write_mol2_with_coordinates(source_mol2, INPUTS / "threitol.mol2", "threitol_(2S,3S)", threitol)
    write_mol2_with_coordinates(source_mol2, INPUTS / "meso_erythritol.mol2", "meso_erythritol_(2S,3R)", meso)
    copy_force_field_files("eryth", "threitol")
    copy_force_field_files("eryth", "meso_erythritol")
    add_c3_chirality_restraint(
        "meso_erythritol",
        ("C3", "C4", "C2", "O3"),
        ("CG311", "CG321", "CG311", "OG311"),
    )
    add_c3_chirality_restraint(
        "threitol",
        ("C3", "C2", "C4", "O3"),
        ("CG311", "CG311", "CG321", "OG311"),
    )

    for stem in ("gly", "xylitol", "sorb"):
        for suffix in ("sdf", "mol2", "rtf", "prm", "str"):
            source = SOURCE / f"{stem}.{suffix}"
            if source.exists():
                shutil.copyfile(source, INPUTS / source.name)

    (INPUTS / "mol_list_pair.txt").write_text("meso_erythritol\nthreitol\n")
    (INPUTS / "mol_list_series.txt").write_text(
        "meso_erythritol\nthreitol\ngly\nxylitol\nsorb\n"
    )
    (INPUTS / "mol_list_corrected_original_series.txt").write_text(
        "meso_erythritol\ngly\nxylitol\nsorb\n"
    )

    # Reload both output formats so the generated inputs, rather than only the
    # in-memory structures, are validated.
    for stem, expected in (("meso_erythritol", ["R", "S"]), ("threitol", ["S", "S"])):
        sdf_mol = Chem.SDMolSupplier(str(INPUTS / f"{stem}.sdf"), removeHs=False)[0]
        mol2_mol = Chem.MolFromMol2File(str(INPUTS / f"{stem}.mol2"), removeHs=False)
        for label, molecule in (("SDF", sdf_mol), ("MOL2", mol2_mol)):
            if molecule is None:
                raise RuntimeError(f"RDKit could not reload {stem} {label}")
            observed = sorted(code for _, code in cip_centres(molecule))
            if observed != expected:
                raise RuntimeError(f"{stem} {label}: expected {expected}, got {observed}")
        print(f"{stem}: SDF {cip_centres(sdf_mol)}; MOL2 {cip_centres(mol2_mol)}")


if __name__ == "__main__":
    main()
